//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdiGatelog
{
    using System;
    using System.Collections.Generic;
    
    public partial class GateInOut
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public int UserId { get; set; }
        public int VehicleTypeId { get; set; }
        public string PlateNumber { get; set; }
        public int PurposeId { get; set; }
        public int ItemsToDeclareId { get; set; }
    
        public virtual ItemsToDeclare ItemsToDeclare { get; set; }
        public virtual Purpose Purpose { get; set; }
        public virtual User User { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
